[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"
[tool.coverage.run]
omit = [
    "nms/config/settings.py",
    "nms/config/urls.py",
    "nms/config/asgi.py",
    "nms/config/wsgi.py",

]