# Generated by Django 4.1.1 on 2022-09-14 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(
                    default=datetime.datetime(
                        2022, 9, 14, 16, 2, 16, 849824,
                        tzinfo=datetime.timezone.utc))),
                ('custom_unique_feild', models.CharField(
                    max_length=250, unique=True)),
            ],
        ),
    ]
