# Generated by Django 4.1.1 on 2022-10-16 10:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clients_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelManagers(
            name='clients',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
