# Generated by Django 4.1.1 on 2022-10-16 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_bandwidth_untermination_date'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='package',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.bandwidth'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date_payed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
