# Generated by Django 4.1.1 on 2022-09-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_clients_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('package', models.CharField(max_length=5)),
                ('start_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='client.clients')),
            ],
        ),
    ]
